name: "WordPress Deployment Action"
description: "Easily deploy code from GitHub to WordPress on Pressable or WP Engine using an SSH private key and the rsync command."
branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  SERVER_TYPE:
    description: "The type of server to deploy to. Use 'pressable' or 'wpengine' for quick plug-and-play or 'custom' for custom SSH connections."
    required: true
  SSH_PRIVATE_KEY:
    description: "The private SSH key. You must save this in GitHub Secrets and authorize it on your server."
    required: true
  SERVER_ID:
    description: "The SSH username for Pressable deployments or the install name for WP Engine deployments. Not used in custom mode."
    required: false
    default: ""
  REMOTE_PATH:
    description: "The remote path on the server where files should be deployed. Defaults to the site root directory."
    default: ""
    required: false
  SRC_PATH:
    description: "Local path to the source files to deploy. Defaults to the repository root."
    default: "."
    required: false
  FLAGS:
    description: "Rsync flags to control the behavior of file synchronization."
    default: "-azvrhi --inplace --exclude='.*'"
    required: false
  PHP_LINT:
    description: "Set to 'TRUE' to enable PHP linting before deployment. Defaults to 'FALSE'."
    default: "FALSE"
    required: false
  CACHE_CLEAR:
    description: "Set to 'TRUE' to clear cache after deployment. Defaults to 'FALSE'."
    default: "FALSE"
    required: false
  SCRIPT:
    description: "Custom script to run on the remote server after deployment."
    default: ""
    required: false
  SSH_USER:
    description: "The SSH username. Only used when SERVER_TYPE is 'custom'."
    required: false
    default: ""
  SSH_HOST:
    description: "The SSH hostname. Only used when SERVER_TYPE is 'custom'."
    required: false
    default: ""
  SSH_DEST:
    description: "The full destination directory. Only used when SERVER_TYPE is 'custom'."
    required: false
    default: ""
  SSH_PORT:
    description: "The SSH port. Only used when SERVER_TYPE is 'custom'. Defaults to 22."
    required: false
    default: "22"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    SERVER_TYPE: ${{ inputs.SERVER_TYPE }}
    SSH_PRIVATE_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
    SERVER_ID: ${{ inputs.SERVER_ID }}
    REMOTE_PATH: ${{ inputs.REMOTE_PATH }}
    SRC_PATH: ${{ inputs.SRC_PATH }}
    FLAGS: ${{ inputs.FLAGS }}
    PHP_LINT: ${{ inputs.PHP_LINT }}
    CACHE_CLEAR: ${{ inputs.CACHE_CLEAR }}
    SCRIPT: ${{ inputs.SCRIPT }}
    SSH_USER: ${{ inputs.SSH_USER }}
    SSH_HOST: ${{ inputs.SSH_HOST }}
    SSH_DEST: ${{ inputs.SSH_DEST }}
    SSH_PORT: ${{ inputs.SSH_PORT }}
